-- COACH SOCCER LAB - Supabase schema completo
create extension if not exists "uuid-ossp";

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  club_name text,
  global_role text default 'user' check (global_role in ('owner','admin','user')),
  status text default 'active' check (status in ('active','blocked')),
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists app_settings (id uuid primary key default uuid_generate_v4(), public_registrations_enabled boolean default true, invite_only_enabled boolean default false, beta_mode_enabled boolean default false, maintenance_mode_enabled boolean default false, free_plan_enabled boolean default true, payments_enabled boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists app_invites (id uuid primary key default uuid_generate_v4(), email text not null, invited_by uuid references profiles(id), status text default 'pending' check(status in ('pending','accepted','revoked','expired')), plan text default 'free', expires_at timestamptz, accepted_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists user_subscriptions (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id) on delete cascade, plan_code text default 'free', status text default 'free' check(status in ('free','trialing','active','past_due','canceled')), trial_ends_at timestamptz, current_period_start timestamptz, current_period_end timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists subscription_plans (id uuid primary key default uuid_generate_v4(), plan_code text unique not null, plan_name text, description text, monthly_price numeric default 0, yearly_price numeric default 0, max_seasons int, max_players int, max_observations int, max_staff_members int, can_export_excel boolean default false, can_import_excel boolean default false, can_use_analytics boolean default false, can_share_season boolean default false, can_use_ipo boolean default false, can_use_advanced_dashboard boolean default false, can_use_pdf_reports boolean default false, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists feature_flags (id uuid primary key default uuid_generate_v4(), feature_key text unique not null, feature_name text, description text, is_globally_enabled boolean default true, enabled_for_free boolean default false, enabled_for_pro boolean default true, enabled_for_team boolean default true, enabled_for_founder boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());

create table if not exists players (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id) on delete cascade, nome text, cognome text, data_nascita date, ruolo text, categoria text, squadra text, numero text, peso_kg numeric, altezza_cm numeric, nickname text, piede_forte text, dettagli_ruolo text, impressione_generale text, source_type text default 'mercato' check(source_type in ('mercato','rosa','entrambi')), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists observations (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id) on delete cascade, player_id uuid references players(id) on delete set null, data_osservazione date, nome text, cognome text, squadra_partita text, ruolo text, categoria text, competizione text, numero text, data_nascita date, peso_kg numeric, altezza_cm numeric, nickname text, piede_forte text, dettagli_ruolo text, fase_possesso text, fase_non_possesso text, transizioni text, caratteristiche_comportamentali_mentali text, punti_forza text, punti_debolezza text, impressione_generale text, corner numeric, punizione numeric, rigore numeric, rimessa_laterale numeric, attitudine_schemi numeric, passaggio numeric, stop numeric, conduzione numeric, tiro numeric, lancio numeric, colpo_testa numeric, tecnica_individuale numeric, tattica_collettiva numeric, anticipo numeric, intercetto numeric, contrasto numeric, marcatura_uomo numeric, marcatura_zona numeric, intervento_scivolata numeric, indirizzamento_avversario numeric, postura_difensiva numeric, duello_aereo numeric, recupero_palloni numeric, dribbling numeric, finalizzazione numeric, tiro_distanza numeric, creativita numeric, cross numeric, filtrante numeric, rifinitura numeric, concentrazione numeric, personalita numeric, coraggio numeric, determinazione numeric, leadership numeric, lavoro_squadra numeric, impegno numeric, comunicazione numeric, rischio numeric, ego numeric, rispetto_regole numeric, velocita numeric, accelerazione numeric, agilita numeric, forza numeric, resistenza numeric, salto numeric, rapidita numeric, altezza numeric, muscolatura numeric, abilita_tecniche_portiere numeric, parata_tuffo numeric, uscite_basse numeric, uscite_alte numeric, rinvio_piedi numeric, rinvio_mani numeric, posizionamento_pali numeric, scelta_tempi numeric, organizzazione_difesa numeric, senso_tattico numeric, copertura_spazio_avanti numeric, media_tecnica numeric, media_tattica numeric, media_difensiva numeric, media_offensiva numeric, media_mentale numeric, media_fisica numeric, media_portiere numeric, media_generale numeric, created_at timestamptz default now(), updated_at timestamptz default now());

create table if not exists seasons (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id), owner_user_id uuid references profiles(id), name text not null, team_name text, category text, notes text, start_date date, end_date date, is_active boolean default false, is_shared boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists season_members (id uuid primary key default uuid_generate_v4(), season_id uuid references seasons(id) on delete cascade, user_id uuid references profiles(id) on delete cascade, invited_email text, role text default 'viewer' check(role in ('owner','admin','editor','analyst','viewer')), status text default 'pending' check(status in ('pending','accepted','revoked')), can_view boolean default true, can_edit_results boolean default false, can_edit_attendance boolean default false, can_edit_roster boolean default false, can_edit_analytics boolean default false, can_manage_members boolean default false, invited_by uuid references profiles(id), accepted_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists season_roster (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id), season_id uuid references seasons(id) on delete cascade, player_id uuid references players(id) on delete set null, nome text, cognome text, ruolo_preferito text, altri_ruoli text, numero_maglia text, attivo boolean default true, note text, created_by uuid references profiles(id), updated_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists season_matches (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id), season_id uuid references seasons(id) on delete cascade, data_partita date, competizione text, giornata text, avversario text, venue text check(venue in ('Casa','Trasferta','Neutro') or venue is null), campo text, gol_fatti int default 0, gol_subiti int default 0, risultato_calcolato text, esito text, note text, created_by uuid references profiles(id), updated_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists season_attendance (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id), season_id uuid references seasons(id) on delete cascade, match_id uuid references season_matches(id) on delete set null, player_id uuid references players(id) on delete set null, nome text, cognome text, data date, tipo text check(tipo in ('Allenamento','Partita','Amichevole','Riunione','Altro') or tipo is null), presente boolean default true, minuti numeric, ruolo text, nota text, cognome_nome text, created_by uuid references profiles(id), updated_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists ipo_event_types (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id) on delete cascade, event_name text not null, default_ipo_score numeric default 0, description text, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists season_analytics_events (id uuid primary key default uuid_generate_v4(), user_id uuid references profiles(id), season_id uuid references seasons(id) on delete cascade, match_id uuid references season_matches(id) on delete set null, data date, gara text, risultato text, competizione text, giornata text, squadra text check(squadra in ('Noi','Avversario') or squadra is null), tipo_evento text, ipo_event_type_id uuid references ipo_event_types(id) on delete set null, giocatore_evento text, cognome_nome text, player_id uuid references players(id) on delete set null, minuto_evento int, zona_evento text, nota_evento text, esito_tiro text, tipologia_tiro text, esito_palla_inattiva text, zona_inizio_azione text, giocatore_rifinitura text, rifinitore_player_id uuid references players(id) on delete set null, zona_rifinitura text, zona_recupero_palla text, punteggio_ipo numeric, created_by uuid references profiles(id), updated_by uuid references profiles(id), created_at timestamptz default now(), updated_at timestamptz default now());

create index if not exists idx_players_user on players(user_id);
create index if not exists idx_observations_user_player on observations(user_id, player_id);
create index if not exists idx_seasons_owner on seasons(owner_user_id);
create index if not exists idx_members_season_user on season_members(season_id,user_id,status);
create index if not exists idx_matches_season on season_matches(season_id);
create index if not exists idx_attendance_season on season_attendance(season_id);
create index if not exists idx_roster_season on season_roster(season_id);
create index if not exists idx_analytics_season on season_analytics_events(season_id);

create or replace function is_global_admin() returns boolean language sql stable security definer as $$ select exists(select 1 from profiles where id=auth.uid() and global_role in ('owner','admin') and status='active'); $$;
create or replace function can_access_season(p_season_id uuid) returns boolean language sql stable security definer as $$ select exists(select 1 from seasons s where s.id=p_season_id and s.owner_user_id=auth.uid()) or exists(select 1 from season_members sm where sm.season_id=p_season_id and sm.user_id=auth.uid() and sm.status='accepted' and sm.can_view=true); $$;
create or replace function can_edit_season_area(p_season_id uuid, p_area text) returns boolean language sql stable security definer as $$ select exists(select 1 from seasons s where s.id=p_season_id and s.owner_user_id=auth.uid()) or exists(select 1 from season_members sm where sm.season_id=p_season_id and sm.user_id=auth.uid() and sm.status='accepted' and ((p_area='results' and sm.can_edit_results) or (p_area='attendance' and sm.can_edit_attendance) or (p_area='roster' and sm.can_edit_roster) or (p_area='analytics' and sm.can_edit_analytics) or (p_area='members' and sm.can_manage_members))); $$;
create or replace function set_active_season(p_season_id uuid) returns void language plpgsql security definer as $$ begin update seasons set is_active=false where owner_user_id=auth.uid(); update seasons set is_active=true where id=p_season_id and (owner_user_id=auth.uid() or can_access_season(p_season_id)); end; $$;
create or replace function handle_new_user() returns trigger language plpgsql security definer as $$ begin insert into profiles(id,email,full_name,club_name,global_role,status) values(new.id,new.email,new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'club_name',case when lower(new.email)=lower(coalesce(new.raw_user_meta_data->>'owner_email','')) then 'owner' else 'user' end,'active') on conflict(id) do nothing; insert into user_subscriptions(user_id,plan_code,status) values(new.id,'free','free') on conflict do nothing; update app_invites set status='accepted', accepted_at=now() where lower(email)=lower(new.email) and status='pending'; update season_members set user_id=new.id, status='accepted', accepted_at=now() where lower(invited_email)=lower(new.email) and status='pending'; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users; create trigger on_auth_user_created after insert on auth.users for each row execute function handle_new_user();

alter table profiles enable row level security; alter table app_settings enable row level security; alter table app_invites enable row level security; alter table user_subscriptions enable row level security; alter table subscription_plans enable row level security; alter table feature_flags enable row level security; alter table players enable row level security; alter table observations enable row level security; alter table seasons enable row level security; alter table season_members enable row level security; alter table season_roster enable row level security; alter table season_matches enable row level security; alter table season_attendance enable row level security; alter table ipo_event_types enable row level security; alter table season_analytics_events enable row level security;

create policy profiles_self_select on profiles for select using (id=auth.uid() or is_global_admin()); create policy profiles_self_update on profiles for update using (id=auth.uid() or is_global_admin());
create policy app_settings_admin_all on app_settings for all using (is_global_admin()) with check (is_global_admin()); create policy app_settings_read_public on app_settings for select using (true);
create policy app_invites_admin_all on app_invites for all using (is_global_admin()) with check (is_global_admin()); create policy app_invites_public_pending_select on app_invites for select using (status='pending' and (expires_at is null or expires_at > now()));
create policy user_subs_read on user_subscriptions for select using (user_id=auth.uid() or is_global_admin()); create policy user_subs_admin_update on user_subscriptions for all using (is_global_admin()) with check (is_global_admin());
create policy plans_read on subscription_plans for select using (auth.uid() is not null); create policy plans_admin_all on subscription_plans for all using (is_global_admin()) with check (is_global_admin());
create policy flags_read on feature_flags for select using (auth.uid() is not null); create policy flags_admin_all on feature_flags for all using (is_global_admin()) with check (is_global_admin());
create policy players_own_all on players for all using (user_id=auth.uid() or is_global_admin()) with check (user_id=auth.uid() or is_global_admin());
create policy observations_own_all on observations for all using (user_id=auth.uid() or is_global_admin()) with check (user_id=auth.uid() or is_global_admin());
create policy seasons_access_select on seasons for select using (owner_user_id=auth.uid() or can_access_season(id) or is_global_admin()); create policy seasons_owner_all on seasons for all using (owner_user_id=auth.uid() or is_global_admin()) with check (owner_user_id=auth.uid() or is_global_admin());
create policy members_access_select on season_members for select using (can_access_season(season_id) or is_global_admin()); create policy members_manage_all on season_members for all using (can_edit_season_area(season_id,'members') or is_global_admin()) with check (can_edit_season_area(season_id,'members') or is_global_admin());
create policy roster_access_select on season_roster for select using (can_access_season(season_id) or is_global_admin()); create policy roster_edit_all on season_roster for all using (can_edit_season_area(season_id,'roster') or is_global_admin()) with check (can_edit_season_area(season_id,'roster') or is_global_admin());
create policy matches_access_select on season_matches for select using (can_access_season(season_id) or is_global_admin()); create policy matches_edit_all on season_matches for all using (can_edit_season_area(season_id,'results') or is_global_admin()) with check (can_edit_season_area(season_id,'results') or is_global_admin());
create policy attendance_access_select on season_attendance for select using (can_access_season(season_id) or is_global_admin()); create policy attendance_edit_all on season_attendance for all using (can_edit_season_area(season_id,'attendance') or is_global_admin()) with check (can_edit_season_area(season_id,'attendance') or is_global_admin());
create policy analytics_access_select on season_analytics_events for select using (can_access_season(season_id) or is_global_admin()); create policy analytics_edit_all on season_analytics_events for all using (can_edit_season_area(season_id,'analytics') or is_global_admin()) with check (can_edit_season_area(season_id,'analytics') or is_global_admin());
create policy ipo_own_all on ipo_event_types for all using (user_id=auth.uid() or is_global_admin()) with check (user_id=auth.uid() or is_global_admin());

insert into app_settings(public_registrations_enabled,invite_only_enabled,beta_mode_enabled,maintenance_mode_enabled,free_plan_enabled,payments_enabled) select true,false,false,false,true,false where not exists(select 1 from app_settings);
insert into subscription_plans(plan_code,plan_name,description,monthly_price,yearly_price,max_seasons,max_players,max_observations,max_staff_members,can_export_excel,can_import_excel,can_use_analytics,can_share_season,can_use_ipo,can_use_advanced_dashboard,can_use_pdf_reports) values
('free','Free','Prova base con limiti',0,0,1,30,50,1,false,false,false,false,false,false,false),('pro','Pro','Allenatore singolo professionale',9,89,999,500,999999,1,true,true,true,false,true,true,false),('team','Team','Staff tecnico con condivisione',19,199,999,999999,999999,10,true,true,true,true,true,true,false),('founder','Founder','Early adopter tutto incluso',0,79,999999,999999,999999,999,true,true,true,true,true,true,true) on conflict(plan_code) do nothing;
insert into feature_flags(feature_key,feature_name,enabled_for_free,enabled_for_pro,enabled_for_team,enabled_for_founder) values
('database_players','Database Giocatori',true,true,true,true),('market_observations','Osservazioni Mercato',true,true,true,true),('season_management','Gestione Stagioni',true,true,true,true),('season_sharing','Condivisione Staff',false,false,true,true),('attendance','Presenze',true,true,true,true),('roster','Rosa',true,true,true,true),('results','Risultati',true,true,true,true),('analytics','Analytics',false,true,true,true),('ipo_events','Eventi IPO',false,true,true,true),('excel_export','Export Excel',false,true,true,true),('excel_import','Import Excel',false,true,true,true),('advanced_dashboard','Dashboard Avanzata',false,true,true,true),('pdf_reports','Report PDF',false,false,false,true),('multi_season_history','Storico Multi-stagione',false,true,true,true) on conflict(feature_key) do nothing;
